--------------------------------------------------------
-- Archivo creado  - lunes-mayo-19-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALUMNOS
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."ALUMNOS" 
   (	"NOMBRE" VARCHAR2(15 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(13 BYTE), 
	"FECHANAC" DATE, 
	"SEXO" CHAR(3 BYTE), 
	"CLAVE" CHAR(8 BYTE), 
	"CIUDAD" VARCHAR2(25 BYTE) DEFAULT 'Morelia', 
	"CARRERA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARRERA
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."CARRERA" 
   (	"CLAVE" VARCHAR2(4 BYTE), 
	"DESCRIPCION" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."CIUDADES" 
   (	"CIUDAD" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."DEPARTAMENTO" 
   (	"NUMERO" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DIRECTOR" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."ESTUDIANTES" 
   (	"NCONTROL" VARCHAR2(8 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"CARRERA" CHAR(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY LIST ("CARRERA") 
  SUBPARTITION BY LIST ("SEXO") 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION "MASCULINO" VALUES ( 'M' ), 
    SUBPARTITION "FEMENINO" VALUES ( 'F' ) ) 
 (PARTITION "ISC"  VALUES ('ISC') 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" , 
 PARTITION "IGE"  VALUES ('IGE') 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GESTIÓN" ) ;
--------------------------------------------------------
--  DDL for Table EXPEDIENTE
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."EXPEDIENTE" 
   (	"NCONTROL" VARCHAR2(8 BYTE), 
	"CLAVEMAT" VARCHAR2(5 BYTE), 
	"CALIF" NUMBER(*,0), 
	"FECHA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESCOLAR" 
  PARTITION BY RANGE ("FECHA") INTERVAL (NUMTOYMINTERVAL (1,'YEAR')) 
 (PARTITION "CICLO_01"  VALUES LESS THAN (TO_DATE(' 2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESCOLAR" ) ;
--------------------------------------------------------
--  DDL for Table MAESTRO
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."MAESTRO" 
   (	"CLAVE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PLAZA" CHAR(5 BYTE), 
	"JEFE" NUMBER(5,0), 
	"EDAD" NUMBER(2,0), 
	"SEXO" CHAR(3 BYTE), 
	"INGRESO" DATE DEFAULT SYSDATE, 
	"DEPTO" NUMBER(2,0), 
	"CURP" CHAR(18 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY RANGE ("EDAD") 
 (PARTITION "JÓVENES"  VALUES LESS THAN (45) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "MADUROS"  VALUES LESS THAN (60) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "RUCOS"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) ;
--------------------------------------------------------
--  DDL for Table MATERIALS
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."MATERIALS" 
   (	"CLAVE" VARCHAR2(5 BYTE), 
	"NONBREMAT" VARCHAR2(25 BYTE), 
	"CARRERA" CHAR(3 BYTE), 
	"SEMESTRE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY LIST ("CARRERA") 
 (PARTITION "ISC"  VALUES ('ISC') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" , 
 PARTITION "IGE"  VALUES ('IGE') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GESTIÓN" , 
 PARTITION "OTROS"  VALUES (DEFAULT) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESCOLAR" ) ;
--------------------------------------------------------
--  DDL for Table PLAZA
--------------------------------------------------------

  CREATE TABLE "C##Escolar"."PLAZA" 
   (	"CLAVE" CHAR(5 BYTE), 
	"NOMBRE" CHAR(30 BYTE), 
	"SUELDO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into "C##Escolar".ALUMNOS
SET DEFINE OFF;
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('Juan','Mena','4523111690',to_date('10/08/98','DD/MM/RR'),'MAS','23120345','Uruapan','ISIS');
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('Marcela','Lara','3532346710',to_date('19/02/01','DD/MM/RR'),'FEM','23120346','Jiquilpan','LIAR');
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('Aurora','Balderas','5555346211',to_date('24/05/02','DD/MM/RR'),'FEM','22120325','Morelia','LIDE');
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('Javier','Herrera','4433121570',to_date('26/11/98','DD/MM/RR'),'MAS','21120123','Morelia','ICVL');
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('Dora','Mijares',null,to_date('16/09/99','DD/MM/RR'),'FEM','21120156','Morelia','MECI');
Insert into "C##Escolar".ALUMNOS (NOMBRE,APELLIDO,TELEFONO,FECHANAC,SEXO,CLAVE,CIUDAD,CARRERA) values ('kevin','Torres','4432435897',to_date('16/03/02','DD/MM/RR'),'MAS','23120396','Zamora','ISIS');
REM INSERTING into "C##Escolar".CARRERA
SET DEFINE OFF;
Insert into "C##Escolar".CARRERA (CLAVE,DESCRIPCION) values ('LIAR','Arquitecto');
Insert into "C##Escolar".CARRERA (CLAVE,DESCRIPCION) values ('ICVL','Ingeniero Civil');
Insert into "C##Escolar".CARRERA (CLAVE,DESCRIPCION) values ('ISIS','Ingeniero en Sistemas');
Insert into "C##Escolar".CARRERA (CLAVE,DESCRIPCION) values ('LIDE','Licenciado en Derecho');
Insert into "C##Escolar".CARRERA (CLAVE,DESCRIPCION) values ('MECI','Medico Cirujano');
REM INSERTING into "C##Escolar".CIUDADES
SET DEFINE OFF;
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Jiquilpan');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Maravatio');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Morelia');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Quiroga');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Uruapan');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Zacapu');
Insert into "C##Escolar".CIUDADES (CIUDAD) values ('Zamora');
REM INSERTING into "C##Escolar".DEPARTAMENTO
SET DEFINE OFF;
REM INSERTING into "C##Escolar".ESTUDIANTES
SET DEFINE OFF;
Insert into "C##Escolar".ESTUDIANTES (NCONTROL,NOMBRE,APELLIDO,SEXO,CARRERA) values ('21120321','Juan','Aviles','M','ISC');
Insert into "C##Escolar".ESTUDIANTES (NCONTROL,NOMBRE,APELLIDO,SEXO,CARRERA) values ('21120179','Ana','Torres','F','ISC');
Insert into "C##Escolar".ESTUDIANTES (NCONTROL,NOMBRE,APELLIDO,SEXO,CARRERA) values ('21120463','Pedro','Vela','M','IGE');
Insert into "C##Escolar".ESTUDIANTES (NCONTROL,NOMBRE,APELLIDO,SEXO,CARRERA) values ('21120123','Luisa','Ramos','F','IGE');
REM INSERTING into "C##Escolar".EXPEDIENTE
SET DEFINE OFF;
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120321','SC-32','90',to_date('21/11/22','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120179','SC-32','79',to_date('31/05/23','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120123','IG-53','99',to_date('01/08/23','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120321','SC-61','93',to_date('30/09/23','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120179','SC-61','87',to_date('16/03/24','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120463','IG-53','95',to_date('11/05/24','DD/MM/RR'));
Insert into "C##Escolar".EXPEDIENTE (NCONTROL,CLAVEMAT,CALIF,FECHA) values ('21120321','SC-94','89',to_date('04/05/25','DD/MM/RR'));
REM INSERTING into "C##Escolar".MAESTRO
SET DEFINE OFF;
REM INSERTING into "C##Escolar".MATERIALS
SET DEFINE OFF;
Insert into "C##Escolar".MATERIALS (CLAVE,NONBREMAT,CARRERA,SEMESTRE) values ('SC-61','Programación Web','ISC','6');
Insert into "C##Escolar".MATERIALS (CLAVE,NONBREMAT,CARRERA,SEMESTRE) values ('SC-32','Estructura de datos','ISC','3');
Insert into "C##Escolar".MATERIALS (CLAVE,NONBREMAT,CARRERA,SEMESTRE) values ('SC-94','Inteligencia artificial','ISC','9');
Insert into "C##Escolar".MATERIALS (CLAVE,NONBREMAT,CARRERA,SEMESTRE) values ('IG-53','Mercadotecnia','IGE','5');
Insert into "C##Escolar".MATERIALS (CLAVE,NONBREMAT,CARRERA,SEMESTRE) values ('TC-35','Algebra lineal','TC ','3');
REM INSERTING into "C##Escolar".PLAZA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008337
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008337" ON "C##Escolar"."ALUMNOS" ("CLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INDICE
--------------------------------------------------------

  CREATE INDEX "C##Escolar"."INDICE" ON "C##Escolar"."ALUMNOS" ("NOMBRE", "APELLIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008341
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008341" ON "C##Escolar"."CARRERA" ("CLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008342
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008342" ON "C##Escolar"."CARRERA" ("DESCRIPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008338
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008338" ON "C##Escolar"."CIUDADES" ("CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."DEPARTAMENTO_PK" ON "C##Escolar"."DEPARTAMENTO" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008356
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008356" ON "C##Escolar"."ESTUDIANTES" ("NCONTROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008357
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008357" ON "C##Escolar"."EXPEDIENTE" ("NCONTROL", "CLAVEMAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESCOLAR" ;
--------------------------------------------------------
--  DDL for Index NUEVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."NUEVA_PK" ON "C##Escolar"."MAESTRO" ("CLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURP_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."CURP_UN" ON "C##Escolar"."MAESTRO" ("CURP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008350
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."SYS_C008350" ON "C##Escolar"."MATERIALS" ("CLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAZA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##Escolar"."PLAZA_PK" ON "C##Escolar"."PLAZA" ("CLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ALUMNOS
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."ALUMNOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."ALUMNOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."ALUMNOS" MODIFY ("FECHANAC" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."ALUMNOS" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."ALUMNOS" ADD CHECK (Sexo IN ('MAS','FEM')) ENABLE;
  ALTER TABLE "C##Escolar"."ALUMNOS" ADD PRIMARY KEY ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRERA
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."CARRERA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."CARRERA" ADD PRIMARY KEY ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##Escolar"."CARRERA" ADD UNIQUE ("DESCRIPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."CIUDADES" ADD PRIMARY KEY ("CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."DEPARTAMENTO" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."DEPARTAMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##Escolar"."DEPARTAMENTO" MODIFY ("DIRECTOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."ESTUDIANTES" ADD PRIMARY KEY ("NCONTROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."EXPEDIENTE" ADD PRIMARY KEY ("NCONTROL", "CLAVEMAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESCOLAR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MAESTRO
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."MAESTRO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."MAESTRO" MODIFY ("DEPTO" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "NOMBRE_MAY" CHECK (NOMBRE=UPPER(NOMBRE)) ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "NUEVA_PK" PRIMARY KEY ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "CURP_UN" UNIQUE ("CURP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "EDAD_CK" CHECK ("EDAD" > 20) ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "SEXO_CK" CHECK ("SEXO" IN ('MAS','FEM')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALS
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."MATERIALS" ADD PRIMARY KEY ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLAZA
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."PLAZA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##Escolar"."PLAZA" ADD CONSTRAINT "PLAZA_PK" PRIMARY KEY ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALUMNOS
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."ALUMNOS" ADD CONSTRAINT "CIUDAD_FK" FOREIGN KEY ("CIUDAD")
	  REFERENCES "C##Escolar"."CIUDADES" ("CIUDAD") ENABLE;
  ALTER TABLE "C##Escolar"."ALUMNOS" ADD CONSTRAINT "CARRERAFK" FOREIGN KEY ("CARRERA")
	  REFERENCES "C##Escolar"."CARRERA" ("CLAVE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPEDIENTE
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."EXPEDIENTE" ADD CONSTRAINT "FK_ESTUDIANTES_NCONTROL" FOREIGN KEY ("NCONTROL")
	  REFERENCES "C##Escolar"."ESTUDIANTES" ("NCONTROL") ENABLE;
  ALTER TABLE "C##Escolar"."EXPEDIENTE" ADD CONSTRAINT "FK_MATERIALS_CLAVE" FOREIGN KEY ("CLAVEMAT")
	  REFERENCES "C##Escolar"."MATERIALS" ("CLAVE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAESTRO
--------------------------------------------------------

  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "NUEVA_FK" FOREIGN KEY ("JEFE")
	  REFERENCES "C##Escolar"."MAESTRO" ("CLAVE") ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "DEPTO_FK" FOREIGN KEY ("DEPTO")
	  REFERENCES "C##Escolar"."DEPARTAMENTO" ("NUMERO") ENABLE;
  ALTER TABLE "C##Escolar"."MAESTRO" ADD CONSTRAINT "PLAZA_FK" FOREIGN KEY ("PLAZA")
	  REFERENCES "C##Escolar"."PLAZA" ("CLAVE") ENABLE;
